# Generated by Django 5.0.7 on 2024-07-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='RELEASE_YEAR',
            new_name='release_year',
        ),
    ]
