# Generated by Django 5.0.7 on 2024-07-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_release_year_movie_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='gerne',
            new_name='genre',
        ),
    ]
